root = "."
tmp_dir = "tmp/air"

[build]
  cmd = "go build -o ./tmp/air/kong-cert-lite ./cmd/kong-cert-lite"
  delay = 1000
  entrypoint = "./tmp/air/kong-cert-lite"
  exclude_dir = ["data", "tmp", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = ["cmd", "internal"]
  include_ext = ["go", "html", "css", "js", "sql"]
  kill_delay = "500ms"
  log = "air-build.log"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
